import React from 'react';

const BackArrowIcon: React.FC = () => (
    <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 mr-2" viewBox="0 0 20 20" fill="currentColor">
        <path fillRule="evenodd" d="M9.707 16.707a1 1 0 01-1.414 0l-6-6a1 1 0 010-1.414l6-6a1 1 0 011.414 1.414L5.414 9H17a1 1 0 110 2H5.414l4.293 4.293a1 1 0 010 1.414z" clipRule="evenodd" />
    </svg>
);

interface TermsOfServiceProps {
  onBack: () => void;
}

export const TermsOfService: React.FC<TermsOfServiceProps> = ({ onBack }) => {
  return (
    <main className="container mx-auto p-4 md:p-8">
      <div className="max-w-4xl mx-auto bg-dark-blue/80 backdrop-blur-lg rounded-2xl shadow-lg border border-platinum/20 p-6 md:p-10">
        <button
          onClick={onBack}
          className="mb-6 inline-flex items-center text-sm font-semibold text-platinum/80 hover:text-white transition-colors"
          aria-label="Back to main application"
        >
          <BackArrowIcon />
          Back to App
        </button>
        <div className="prose prose-slate max-w-none">
          <h1>Terms of Service</h1>
          <p className="text-sm text-platinum/50">Last Updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>

          <h2>1. Acceptance of Terms</h2>
          <p>By accessing or using the Vestria Style application ("Service"), provided by Gilded Technologies Pvt Ltd, you agree to be bound by these Terms of Service ("Terms"). If you do not agree to all of these Terms, do not use the Service.</p>

          <h2>2. Description of Service</h2>
          <p>The Service is an AI-powered styling application that helps you digitally curate your wardrobe. It provides style compatibility analysis, outfit suggestions, and general fashion advice based on images and information you provide.</p>

          <h2>3. User-Generated Content</h2>
          <p>You retain all ownership rights to the images and content you upload ("User Content"). By uploading User Content, you grant us a non-exclusive, royalty-free, worldwide license to use, reproduce, and process this content solely for the purpose of providing the Service to you.</p>

          <h2>4. AI-Generated Content</h2>
          <p>The Service uses artificial intelligence to generate text and images ("AI Content"), including outfit visualizations and styling advice. This AI Content is provided for informational and entertainment purposes only. You are granted a license to use the AI Content for personal, non-commercial purposes. Gilded Technologies and its licensors retain all ownership rights in the AI models and the Service.</p>

          <h2>5. User Conduct</h2>
          <p>You agree not to use the Service to upload any content that is illegal, harmful, threatening, abusive, defamatory, obscene, or otherwise objectionable.</p>
          
          <h2>6. Disclaimers</h2>
          <p>THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. THE STYLE ADVICE AND RECOMMENDATIONS ARE GENERATED BY AN AI AND SHOULD NOT BE CONSIDERED PROFESSIONAL FASHION ADVICE. GILDED TECHNOLOGIES PVT LTD IS NOT RESPONSIBLE FOR ANY FASHION DECISIONS YOU MAKE BASED ON THE SERVICE'S OUTPUT.</p>

          <h2>7. Limitation of Liability</h2>
          <p>IN NO EVENT SHALL GILDED TECHNOLOGIES PVT LTD BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR PUNITIVE DAMAGES, INCLUDING WITHOUT LIMITATION, LOSS OF PROFITS, DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, RESULTING FROM YOUR ACCESS TO OR USE OF OR INABILITY TO ACCESS OR USE THE SERVICE.</p>

          <h2>8. Changes to Terms</h2>
          <p>We reserve the right to modify these Terms at any time. We will notify you by making the revised Terms available through the Service. Your continued use of the Service after any such change constitutes your acceptance of the new Terms.</p>

          <h2>Contact Us</h2>
          <p>If you have any questions about these Terms, please contact us at: support@vestria.style</p>
        </div>
      </div>
    </main>
  );
};